# Generated by Django 4.0.2 on 2022-04-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
